### ISSUE TITLE
App fails to open if there is no Internet connection

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-mobile-app#11]

**Comment by waynedyck** [comment]
This is likely because of the need to download the external Google Maps JavaScript via the [GWT-Maps-V3-Api](https://github.com/branflake2267/GWT-Maps-V3-Api) library. The app tries to download the library and hangs when it cannot.

We might be able to use the [Connection Module](https://code.google.com/p/gwt-phonegap/wiki/ConnectionModule) in [GWT-PhoneGap](https://code.google.com/p/gwt-phonegap/) to check for the current connection state. If there is not an Internet connection, simply skip loading the library and display a warning message if one tries to access the traffic map.

**Comment by loganSims** [comment]
```
if (phoneGap.getConnection().getType().equals(Connection.NONE)
    || phoneGap.getConnection().getType().equals(Connection.UNKNOWN)){
```
This will fire the app up when connections are turned off. 
If there is a very weak connection it still seems to hang, or at least takes an unreasonably long time to load.

Still need to workout how to handle warning message about traffic map.

**Comment by loganSims** [comment]
[PhoneGap Events Module](https://code.google.com/archive/p/gwt-phonegap/wikis/EventsModule.wiki)
There is an online & offline event.
