### ISSUE TITLE
Ferry Schedules - Friday Harbor to Anacortes error message

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-mobile-app#14]
When viewing the Ferry Schedule for Friday Harbor to Anacortes an error is thrown which says,

**uncaught:for input string null**

Not sure why as the data feed looks fine.

**Comment by waynedyck** [comment]
Today the Port Townsend to Coupeville route is throwing the same error.

**Comment by branflake2267** [comment]
I'm not getting an error for that route.

**Comment by waynedyck** [comment]
Thanks for letting me know. It's hit and miss. I noticed this morning that the Friday Harbor to Anacortes route is throwing an error again as well. I will try and run the app on the desktop this morning and see if I can spot what is causing it.

**Comment by waynedyck** [comment]
Sometimes we turn off the drive-up space indicator due to inaccurate data and a number of other reasons. In the data feed I wasn't checking the `DisplayDriveUpSpace: false` value and as a result was trying to to parse Integer values from `DriveUpSpaceCount` which is `null` in these cases.
