### ISSUE TITLE
Add available cameras at each terminal to Ferries sailing schedule

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-mobile-app#17]
The drive-up spaces available indicator is one tool to help users determine space available on the ferry sailings. Providing easy access to cameras at each terminal will also assist them in seeing vehicles queued outside the tollbooths, which will subtract from the listed available space.

**Comment by waynedyck** [comment]
Thinking of implementing tabs like we do on the Mountain Pass activity. In this case one tab will be labeled, "Departures" and the other "Cameras"

We could also add a "Camera" icon to the Navigation Bar as there is room on the right side.

**Comment by branflake2267** [comment]
nice job

**Comment by waynedyck** [comment]
Thanks. Hopefully folks find it helpful. The changes should be live in the app next week sometime.
