### ISSUE TITLE
Allow for push notifications if high or highest impact alerts exist along the route being traveled. 

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-mobile-app#31]
Possibly allow people to favorite routes and if an alert happens within an area they've defined they can receive a push notification?

**Comment by loganSims** [comment]
Will look into GCM notifications for our app. These notifications will be more general and will not be based on routes being traveled.
* [PhoneGap plugin for push notifications](https://github.com/phonegap/phonegap-plugin-push)

Some helpful links:
* [iOS and GCM plug in docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#ios)
* [Setting up a GCM Client App on iOS](https://developers.google.com/cloud-messaging/ios/client)
* [Provisioning APNs SSL Certificates](https://developers.google.com/cloud-messaging/ios/certs)

**Comment by loganSims** [comment]
We could also go the [APNS](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html) route and possibly use [PyAPNs](https://github.com/djacobs/PyAPNs).

**Comment by loganSims** [comment]
Google is up to something new.
https://firebase.google.com/docs/cloud-messaging/
