### ISSUE TITLE
Unable to display Google Maps element

### ISSUE THREAD

**Issue by au78** [WSDOT/wsdot-mobile-app#53]
On iphone 6 (latest OS), I see the following error message upon loading the traffic map

Alert title: index.html
Error details: This page was unable to display a Google Maps element. Please contact the site administrator. If you are the administrator of this site, please check the JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors

I have tried restarting the phone but does not help. Any idea what is going on?

**Comment by loganSims** [comment]
Google changed their maps service on June 22. We are pretty sure that is what caused the error. The issue has been resolved in version [4.3.1](https://github.com/WSDOT/wsdot-mobile-app/commit/cdafce7eaf2b1c77e5e59073204de47bd8c2f45a). 

However, we have also had reports and tested that older version are now working.

**Comment by au78** [comment]
Thank you. I have downloaded the new version from iOS App Store and this issue is resolved.

**Comment by loganSims** [comment]
Glad to hear it.
