### ISSUE TITLE
My Maven dependencies (mgwt & mgwt-themebase) are not resolving

### ISSUE THREAD

**Issue by jspreddy** [WSDOT/wsdot-mobile-app#58]
These two maven dependencies are not resolving for me.

```xml
<dependency>
	<groupId>com.googlecode.mgwt</groupId>
	<artifactId>mgwt-themebase</artifactId>
	<version>2.0.0-SNAPSHOT</version>
</dependency>
<!-- HTML5 database -->
<dependency>
	<groupId>com.google.code.gwt.database</groupId>
	<artifactId>gwt-html5-database</artifactId>
	<version>1.5.1-SNAPSHOT</version>
</dependency>
```

**No Results** for either of these on `mvnrepository.com`
[https://mvnrepository.com/search?q=mgwt-themebase](url). 
[https://mvnrepository.com/search?q=gwt-html5-database](url)

Need help.

**Comment by loganSims** [comment]
The missing projects can be found here:
[gwt-html5-database](https://github.com/WSDOT/gwt-html5-database)
[mgwt.themebase](https://github.com/mgwt/mgwt.themebase)

Running `mvn install` for both projects will add them to your local maven repo and the app project should be able to find them after.
